//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by nrdbpro.rc
//
#define IDC_NEXT                        3
#define IDR_MAINFRAME                   10
#define IDR_MAPTYPE                     11
#define IDR_REPORTTYPE                  12
#define IDR_GRAPHTYPE                   13
#define IDR_SUMMARYREPORT               14
#define IDR_HTMLHELP                    15
#define IDR_HTMLREPORT                  16
#define IDR_TSGRAPHTYPE                 17
#define IDR_PIECHART                    18
#define IDR_TSREPORT                    19
#define IDR_PROPERTIES                  20
#define IDD_ABOUTBOX                    100
#define IDD_FEATURETYPE                 132
#define IDD_FTYPEATTR                   133
#define IDD_FEATURES                    137
#define IDD_EDITFEATURE                 138
#define IDD_ATTRIBUTES                  139
#define IDD_EDITATTRIBUTES              140
#define IDD_ADDLAYER                    145
#define IDD_MAPLINES                    146
#define IDB_BOHOL2                      148
#define IDD_REPORT                      151
#define IDC_CURSOR1                     153
#define IDC_CURDRAG                     153
#define IDD_IMPORTODBC                  155
#define IDD_IMPORTTABLE                 156
#define IDD_FEATURESEL                  159
#define IDD_FTYPESEL                    160
#define IDD_EDITMAP                     161
#define IDD_MAPLAYERS                   163
#define IDD_QUERY                       164
#define IDD_SELECTFEATURES              167
#define IDD_MAPPROPERTIES               168
#define IDB_TREECTRL                    171
#define IDD_DATES                       173
#define IDC_CURSOR2                     175
#define IDB_TICK                        176
#define IDB_NOTICK                      177
#define IDB_LOGO1                       178
#define IDB_LOGOMASK                    178
#define IDB_LOGO2                       179
#define IDB_LOGO3                       180
#define IDB_LOGO4                       181
#define IDB_LOGO5                       182
#define IDB_LOGO6                       183
#define IDC_CURSOR3                     184
#define IDD_LL2UTM                      185
#define IDD_SELDICTIONARY               186
#define IDB_BITMAP1                     187
#define IDD_IMPORTSTATUS                188
#define IDB_TREECTRL1                   188
#define IDB_LOGO                        188
#define IDD_PROGRESS                    189
#define IDC_CURSOR4                     190
#define IDD_DELETE                      191
#define IDC_CURSOR5                     192
#define IDD_IMPORTDATE                  193
#define IDC_CURSOR6                     195
#define IDD_LOGIN                       198
#define IDC_CURSOR7                     199
#define IDD_SUMMARYREPORT               199
#define IDD_QUERYCALC                   200
#define IDD_QUERYSTATS                  201
#define IDD_PROJECTION                  202
#define IDD_SECTOR                      203
#define IDD_REPORTDETAILS               204
#define IDR_MAPPOPUP                    205
#define IDR_MAPEDIT                     206
#define IDC_CURSOR8                     206
#define IDD_MAPLAYERPROP                208
#define IDD_MAPTEXTPROP                 209
#define IDD_MAPSTYLESPROP               210
#define IDD_REPORTWIZARD                211
#define IDD_REPORTWIZARDTYPE            212
#define IDC_CURSOR9                     212
#define IDD_REPORTWIZARDFEATURE         213
#define IDD_REPORTWIZARDMAP             214
#define IDD_REPORTWIZARDSETUP           215
#define IDD_REPORTGRAPH                 216
#define IDD_SELECTLAYER                 217
#define IDD_MAPLEGENDPROP               218
#define IDD_GRAPHPROP                   220
#define IDC_CURSOR10                    222
#define IDC_DRAGLAYER                   223
#define IDB_PATTERN1                    224
#define IDC_DRAGHORZ                    224
#define IDD_NEW                         225
#define IDC_CURDRAG2                    225
#define IDD_SCALE                       226
#define IDD_LOGIN2                      227
#define IDD_QUERYCOND                   228
#define IDD_IMPORTCREATE                229
#define IDD_IMPORTTABLE2                230
#define IDD_FTYPEATTR2                  231
#define IDD_MAPSTYLESPROP2              232
#define IDD_MAPTEXTPROP2                233
#define IDD_IMPORTSYMBOL                234
#define IDD_IMAGE                       235
#define IDD_MAPLAYERPROP2               236
#define IDD_MAPCOMMENTPROP2             237
#define IDD_SEARCH                      238
#define IDB_UTM                         243
#define IDD_UTM                         244
#define IDD_REGISTER                    247
#define IDD_IMPORTCREATE2               248
#define IDD_QUERYSORT                   249
#define IDD_LAYOUT                      254
#define IDD_LAYOUTTEXT                  255
#define IDD_IMPORTRENAME                256
#define IDD_IMPORTPRIMARYKEY            257
#define IDD_EXPLORER                    258
#define IDR_EXPLORER                    259
#define IDB_BACKGROUND                  260
#define IDD_DIGITIZE                    261
#define IDC_CURPAN                      264
#define IDC_CURSOR11                    265
#define IDD_IMAGEOPTIONS                266
#define IDD_PROTECT                     267
#define IDD_REPORTHTML                  268
#define IDB_POPUPMENU                   268
#define IDR_SCHEME                      269
#define IDD_SAVESCHEME                  270
#define IDR_SYMBOLS                     271
#define IDD_COLORRANGE                  272
#define IDR_MAPLAYOUT                   273
#define IDD_MAPGRID                     276
#define IDD_RENAME                      279
#define IDD_QUERYJOIN                   280
#define IDC_CURSEL                      281
#define IDC_CURINS                      282
#define IDD_VIEWATTR                    283
#define IDD_CONNECT                     284
#define IDD_DBNAME                      285
#define IDB_BITMAP2                     286
#define IDD_MAPFEATURESEL               287
#define IDD_REPORTUNITS                 288
#define IDD_SELECTFEATURES1             289
#define IDR_ADVANCED                    290
#define IDC_FEATURE                     1000
#define IDC_ATTR                        1001
#define IDC_DATETIME                    1002
#define IDC_FTYPE2                      1002
#define IDC_ATTRS                       1002
#define IDC_COND                        1002
#define IDC_FEATURETYPES                1003
#define IDC_ADD                         1004
#define IDC_DELETE                      1005
#define IDC_FTYPENAME                   1006
#define IDC_ATTRIBUTES                  1007
#define IDC_ATTRNAME                    1008
#define IDC_ATTRTYPE                    1009
#define IDC_POLYLINES                   1009
#define IDC_UPDATE                      1010
#define IDC_POLYGONS                    1010
#define IDC_POINTS                      1011
#define IDC_EDIT                        1012
#define IDC_FTYPE                       1013
#define IDC_EDITDATA                    1014
#define IDC_NAME                        1019
#define IDC_FEATURES                    1020
#define IDC_ORGANISATION                1020
#define IDC_OVERLAYS                    1021
#define IDC_FEATURESM                   1021
#define IDC_DATE                        1032
#define IDC_IMPORT                      1033
#define IDC_IMPORT2                     1034
#define IDC_MAPLINES                    1035
#define IDC_IMPORT3                     1035
#define IDC_COLOR                       1036
#define IDC_TEXTCOLOR                   1037
#define IDC_SELCOLOR                    1037
#define IDC_GRID                        1041
#define IDC_FTYPELINK                   1043
#define IDC_PARENTFEATURE               1049
#define IDC_PARENTFYTPE                 1050
#define IDC_HIERARCHY                   1051
#define IDC_DICTIONARY                  1052
#define IDC_DATASOURCE                  1055
#define IDC_TABLES                      1056
#define IDC_COLUMN                      1057
#define IDC_COLUMNATTR                  1058
#define IDC_CONNECT                     1059
#define IDDEFINE                        1060
#define IDC_ADMINISTRATOR               1061
#define IDC_SAVE                        1062
#define IDC_LOAD                        1063
#define IDC_ATTRIBUTE                   1065
#define IDC_SELECT                      1066
#define IDS_FEATURE                     1067
#define IDC_SYSTABLES                   1068
#define IDC_SELECTALL                   1070
#define IDC_DESCRIPTION                 1071
#define IDC_SELECTALLATTR               1071
#define IDC_CREATE                      1076
#define IDC_EDITFEATURE                 1077
#define IDC_CREATEALL                   1077
#define IDC_EDITATTR                    1078
#define IDC_MAPLAYER                    1078
#define IDC_UPDOWN                      1087
#define IDC_PROPERTIES                  1088
#define IDC_PROGRESS                    1089
#define IDC_ELEMENTS                    1091
#define IDC_PARENTFEATURES              1104
#define IDC_SELECTALL2                  1106
#define IDC_SELECTALL1                  1107
#define IDC_FONT                        1109
#define IDC_LINESTYLE                   1110
#define IDC_SYMBOL                      1111
#define IDC_FILLSTYLE                   1112
#define IDC_OVERLAPTEXT                 1113
#define IDC_TEXTPOS                     1114
#define IDC_SCALETEXT                   1115
#define IDC_QUERY                       1118
#define IDC_LAYERNAME                   1119
#define IDC_DATES                       1120
#define IDC_FROM                        1121
#define IDC_TO                          1122
#define IDS_TO                          1123
#define IDC_FEATURESMULT                1127
#define IDC_FEATURESSGL                 1128
#define IDC_STATISTIC                   1130
#define IDC_SORTBY                      1131
#define IDC_ABOUTICON                   1132
#define IDC_GROUPBY                     1132
#define IDC_STATISTIC2                  1133
#define IDC_PRIMARYKEY                  1135
#define IDC_LATITUDE                    1136
#define IDC_LONGITUDE                   1137
#define IDC_UTM                         1138
#define IDC_BUTTON1                     1139
#define IDC_AUTOCOLOR                   1140
#define IDC_BUTTON2                     1140
#define IDC_MIN                         1141
#define IDC_BUTTON3                     1141
#define IDC_MAX                         1142
#define IDC_AUTOSIZE                    1143
#define IDC_TICKS                       1143
#define IDC_POLYGON                     1144
#define IDC_SEPCOLOR                    1144
#define IDC_BUILDDATE                   1145
#define IDC_DICTIONARIES                1146
#define IDC_BUILDDATE2                  1146
#define IDC_STATUS                      1148
#define IDC_PROGRESS1                   1150
#define IDC_TEXT                        1152
#define IDC_PARENT                      1153
#define IDC_DELETEDATA                  1154
#define IDC_DELETEFEATURES              1155
#define IDS_DATES                       1155
#define IDC_DELETEFTYPE                 1156
#define IDC_INCLINKS                    1158
#define IDC_SHOWALLDATA                 1160
#define IDC_ODBCADM                     1164
#define IDC_BESTFITSYM                  1165
#define IDS_PARENT                      1167
#define IDC_SKIP                        1168
#define IDC_ATTR1                       1169
#define IDC_ATTR2                       1170
#define IDC_OPERATOR                    1171
#define IDC_STATSNAME                   1172
#define IDC_QUERYSTATS                  1173
#define IDC_EDITNAME                    1176
#define IDC_DECPLACES                   1176
#define IDC_SEMIMAJORAXIS               1177
#define IDC_SECTOR                      1177
#define IDC_SEMIMINORAXIS               1178
#define IDC_LATITUDEORIGIN              1179
#define IDC_LONGITUDEORIGIN             1180
#define IDC_FALSEEASTING                1181
#define IDC_FALSENORTHING               1182
#define IDC_SCALEFACTOR                 1183
#define IDC_MINEASTING                  1184
#define IDC_MAXEASTING                  1185
#define IDC_MINNORTHING                 1186
#define IDC_MAXNORTHING                 1187
#define IDC_ELIPSOID                    1188
#define IDC_ELLIPSOID                   1188
#define IDC_EXPORT                      1189
#define IDC_SCALECOORDS                 1189
#define IDC_ORGANIZATION                1191
#define IDC_ADDRESS                     1192
#define IDC_CITY                        1193
#define IDC_PROVINCE                    1194
#define IDC_COUNTRY                     1195
#define IDC_TELEPHONE                   1196
#define IDC_FAX                         1197
#define IDC_PROJECT                     1197
#define IDC_EMAIL                       1198
#define IDC_LOGO                        1199
#define IDC_COORDASLATLON               1200
#define IDC_DEBUG                       1201
#define IDC_SEPLAYER                    1202
#define IDC_FILLPOLY                    1203
#define IDC_OPTIONS                     1205
#define IDC_LAYERS                      1206
#define IDC_FEATURENAME                 1209
#define IDS_MINIMUM                     1209
#define IDC_REPORT                      1214
#define IDC_GRAPH                       1215
#define IDS_FTYPE1                      1215
#define IDC_MAP                         1216
#define IDS_FTYPE2                      1216
#define IDC_LATEST                      1217
#define IDC_FTYPE1                      1217
#define IDC_AREA                        1217
#define IDC_HISTORIC                    1218
#define IDC_NUMBERS                     1218
#define IDC_SYMSIZE                     1219
#define IDC_MAPOBJ                      1224
#define IDC_LABEL                       1225
#define IDC_AUTOSTYLE                   1225
#define IDC_LAYER                       1226
#define IDC_COLOURSCHEME                1226
#define IDC_COMMENT                     1227
#define IDC_TITLE                       1228
#define IDC_BROWSE                      1229
#define IDC_FONT1                       1231
#define IDC_FONT2                       1232
#define IDC_LINE                        1233
#define IDC_FONTLEGEND                  1233
#define IDC_STYLE                       1234
#define IDC_TYPE                        1236
#define IDC_SINGLEFONT                  1237
#define IDC_SAMEASLABEL                 1238
#define IDC_LEGEND                      1238
#define IDC_VALUE                       1238
#define IDC_LBCOND                      1239
#define IDC_CBMS                        1239
#define IDS_PARENTFTYPE                 1240
#define IDS_FILLSTYLE                   1241
#define IDC_INSERT                      1242
#define IDC_MAPNEW                      1244
#define IDC_REPORTNEW                   1245
#define IDC_SECTORALREPORTNEW           1246
#define IDC_TSREPORTNEW                 1247
#define IDC_HISTOGRAMNEW                1248
#define IDC_SCALE                       1248
#define IDC_TIMESERIESGRAPHNEW          1249
#define IDC_NEW                         1249
#define IDC_PIECHARTNEW                 1250
#define IDC_ANIMATE1                    1250
#define IDC_FEATUREFROM                 1251
#define IDC_FEATURETO                   1252
#define IDC_AUTOSYM                     1252
#define IDC_PFEATUREFROM                1253
#define IDC_COLORSYM                    1253
#define IDC_PFEATURETO                  1254
#define IDC_AUTOLINE                    1254
#define IDC_GFEATUREFROM                1255
#define IDC_COLORLINE                   1255
#define IDC_GFEATURETO                  1256
#define IDC_AUTOFILL                    1256
#define IDC_COLORFILL                   1257
#define IDC_CUSTOM                      1258
#define IDC_SYMBOLS                     1260
#define IDC_BORDER                      1262
#define IDC_SEARCH                      1263
#define IDC_HOMEPAGE                    1264
#define IDC_ZONE                        1265
#define IDC_DEFAULT                     1266
#define IDS_MERIDIAN                    1266
#define IDC_SETEXTENT                   1267
#define IDC_REGKEY                      1268
#define IDC_REGCODE                     1269
#define IDC_SEND                        1270
#define IDC_REGISTER                    1271
#define IDC_SORTATTR                    1273
#define IDC_TRIAL                       1273
#define IDC_VERSION                     1274
#define IDC_CREDITS                     1275
#define IDC_GRID1                       1277
#define IDC_ITEM                        1278
#define IDC_LAYOUT                      1280
#define IDC_COMBO1                      1282
#define IDC_TREE1                       1282
#define IDC_METHOD                      1282
#define IDC_APPEARANCE                  1282
#define IDC_LENGTH                      1282
#define IDS_COLOURSCHEME                1283
#define IDC_ROUND                       1283
#define IDC_WIDTH                       1285
#define IDC_PROTECT                     1285
#define IDC_HEIGHT                      1286
#define IDC_MESSAGE                     1286
#define IDC_QUALITY                     1287
#define IDC_SHOWLAYERNAME               1287
#define IDC_COLOUR                      1288
#define IDC_EXTENT                      1288
#define IDC_SLIDER                      1289
#define IDC_HEADER                      1290
#define IDC_FOOTER                      1291
#define IDC_USEHEADER                   1292
#define IDC_USEFOOTER                   1293
#define IDC_SCHEMEMENU                  1294
#define IDC_NUMINTERVALS                1296
#define IDC_SYMBOL_MENU                 1297
#define IDC_SYMSAMPLE                   1298
#define IDC_VALUE2                      1299
#define IDC_VALUE1                      1300
#define IDC_DEGLAT                      1300
#define IDC_MINLAT                      1301
#define IDC_SECLAT                      1302
#define IDC_EDIT1                       1302
#define IDC_DEGLNG                      1303
#define IDC_MINLNG                      1304
#define IDC_SECLNG                      1305
#define IDC_RENAME                      1306
#define IDC_AUTOUPDATE                  1308
#define IDC_AUTOMATCH                   1309
#define IDC_ATTRFROM                    1310
#define IDC_ATTRTO                      1311
#define IDC_CONDITION                   1312
#define IDC_DISTANCE                    1313
#define IDC_JOINS                       1314
#define IDC_INCLUSIVE                   1315
#define IDC_EXCLUSIVE                   1316
#define IDC_LIST1                       1316
#define IDC_USERNAME                    1322
#define IDC_PASSWORD                    1323
#define IDC_DATABASE                    1323
#define IDS_ERRORREAD                   10000
#define IDS_SELECTALL                   10001
#define IDS_DESELECTALL                 10002
#define IDS_NONE                        10003
#define IDS_NAME                        10004
#define IDS_EDIT                        10005
#define IDS_DATE                        10006
#define IDS_NODATE                      10007
#define IDS_YES                         10008
#define IDS_NO                          10009
#define IDS_YES1                        10010
#define IDS_NO1                         10011
#define IDS_INVALIDVALUE                10012
#define IDS_DATEFORMAT                  10013
#define IDS_NUMFORMAT                   10014
#define IDS_COORDFORMAT                 10015
#define IDS_LINKFORMAT                  10016
#define IDS_SELMAPOBJ                   10017
#define IDS_NONAMESEL                   10018
#define IDS_NOFTYPESEL                  10019
#define IDS_ERROREXPORT                 10020
#define IDS_OFTYPE                      10021
#define IDS_ONROW                       10022
#define IDS_SAVECHANGES                 10023
#define IDS_NOPARENT                    10024
#define IDS_CONFIRMDELETE               10025
#define IDS_CANNOTDELDATA               10026
#define IDS_DELETED                     10027
#define IDS_NODATATYPE                  10028
#define IDS_NOLINK                      10029
#define IDS_NOTSAVED                    10030
#define IDS_NOPARENTFTYPE               10031
#define IDS_NOSECTOR                    10032
#define IDS_LINKSNOTDEFINE              10033
#define IDS_DATATYPECHANGE              10034
#define IDS_ATTRNAMEINVALID             10035
#define IDS_NOTBLANK                    10036
#define IDS_STICKS                      10037
#define IDS_LINES                       10038
#define IDS_CANNOTDEL                   10039
#define IDS_HISTOGRAMGRAPH              10040
#define IDS_STANDARDREPORT              10041
#define IDS_TIMESERIESGRAPH             10042
#define IDS_NOATTRSEL                   10043
#define IDS_REPORT                      10044
#define IDS_GRAPH                       10045
#define IDS_INITIALIZING                10046
#define IDS_WRITINGREPORT               10047
#define IDS_NOVALUE                     10048
#define IDS_DATEAFTER                   10049
#define IDS_FILEFORMAT                  10050
#define IDS_NODIR                       10051
#define IDS_NOFILE                      10052
#define IDS_IMPORTEDDEF                 10053
#define IDS_IMPORTEDFEATURES            10054
#define IDS_IMPORTEDDATA                10055
#define IDS_FEATUREEXISTS               10056
#define IDS_NOFEATURE                   10057
#define IDS_NOMATCH                     10058
#define IDS_SHAPEFILEFORMAT             10059
#define IDS_ODBCERROR                   10060
#define IDS_EXCELFILE                   10061
#define IDS_ACCESSFILE                  10062
#define IDS_TEXTFILE                    10063
#define IDS_DBASEFILE                   10064
#define IDS_OUTOFMEMORY                 10065
#define IDS_NRDBFILE                    10066
#define IDS_CHANGEDATADICT              10067
#define IDS_ERROROPEN                   10068
#define IDS_AUTOSIZE                    10069
#define IDS_AUTOCOLOR                   10070
#define IDS_LIGHTTODARK                 10071
#define IDS_SEPARATECOLOR               10072
#define IDS_COLORRANGE                  10073
#define IDS_FIRSTTONTH                  10074
#define IDS_LEGENDVALUES                10075
#define IDS_TOPLEFT                     10076
#define IDS_BOTTOMRIGHT                 10077
#define IDS_TOPRIGHT                    10078
#define IDS_BOTTOMLEFT                  10079
#define IDS_CENTER                      10080
#define IDS_BESTFIT                     10081
#define IDS_NONUMSEL                    10082
#define IDS_ATTRIBUTESTIP               10083
#define IDS_STRING10084                 10084
#define IDS_SELNUMTEXT                  10085
#define IDS_SELTEXT                     10086
#define IDS_MEAN                        10087
#define IDS_MAX                         10088
#define IDS_MIN                         10089
#define IDS_TOTAL                       10090
#define IDS_COUNT                       10091
#define IDS_NOGROUPBY                   10092
#define IDS_ADD                         10093
#define IDS_SUBTRACT                    10094
#define IDS_MULTIPLY                    10095
#define IDS_DIVIDE                      10096
#define IDS_PERCENT                     10097
#define IDS_NOCALCNAME                  10098
#define IDS_ADDCALC                     10099
#define IDS_INVALIDSHAPEFILE            10100
#define IDS_SHAPEFILEEXPORTED           10101
#define IDS_EXPORTESUCCESS              10101
#define IDS_NODATALAYER                 10102
#define IDS_SHAPEFILE                   10103
#define IDS_ERRORCONVERT                10104
#define IDS_SAMEFILE                    10105
#define IDS_ERRORDBASE                  10106
#define IDS_ERRORINDEX                  10107
#define IDS_SHAPEFILECONVERTED          10108
#define IDS_NODATA                      10109
#define IDS_INVALIDDATE                 10110
#define IDS_BUILDDATE                   10111
#define IDS_DBASEFORMAT                 10112
#define IDS_ERRORFORMAT                 10113
#define IDS_NOTABLESSEL                 10114
#define IDS_DEFINEIMPORT                10115
#define IDS_REPORTWIZARD                10116
#define IDS_SELINFO                     10117
#define IDS_LOGOUT                      10118
#define IDS_ERRORREPORT                 10119
#define IDS_ERRORWRITE                  10120
#define IDS_ERRORSHAPEFILE              10121
#define IDS_ERRORIMPORT                 10122
#define IDS_POLYLINESFILE               10123
#define IDS_LATLONFILE                  10124
#define IDS_IMPORTING                   10125
#define IDS_IMPORTCANCEL                10126
#define IDS_NUMRECORDS                  10127
#define IDS_IMPORTTIP                   10128
#define IDS_IMPORTSHAPEFILE             10129
#define IDS_OUTSIDEEXTENT               10130
#define IDS_IMPORTED                    10131
#define IDS_UNDEFINED                   10132
#define IDS_TRUE                        10133
#define IDS_FALSE                       10134
#define IDS_NONAME                      10135
#define IDS_INVALIDNRDB                 10136
#define IDS_REPLACELAYERS               10137
#define IDS_POLYLINESTYPE               10138
#define IDS_COORDTYPE                   10139
#define IDS_FILEDSN                     10140
#define IDS_CONVERTLATLON               10141
#define IDS_UTM                         10142
#define IDS_CONVERTTOLATLON             10143
#define IDS_NUMBER                      10144
#define IDS_TEXT                        10145
#define IDS_COORDINATES                 10146
#define IDS_POLYLINES                   10147
#define IDS_LINK                        10148
#define IDS_BOOLEAN                     10149
#define IDS_FILE                        10150
#define IDS_DBASEDRIVER                 10151
#define IDS_ACCESSDRIVER                10152
#define IDS_TEXTDRIVER                  10153
#define IDS_EXCELDRIVER                 10154
#define IDS_N                           10155
#define IDS_S                           10156
#define IDS_E                           10157
#define IDS_W                           10158
#define IDS_DEFAULTFONT                 10159
#define IDS_METERS                      10160
#define IDS_KM                          10161
#define IDS_JAN                         10162
#define IDS_FEB                         10163
#define IDS_MAR                         10164
#define IDS_APR                         10165
#define IDS_MAY                         10166
#define IDS_JUN                         10167
#define IDS_JUL                         10168
#define IDS_AUG                         10169
#define IDS_SEP                         10170
#define IDS_OCT                         10171
#define IDS_NOV                         10172
#define IDS_DEC                         10173
#define IDS_NOPROJECTION                10174
#define IDS_TIPUTM                      10175
#define IDS_DONTIMPORT                  10176
#define IDS_X                           10177
#define IDS_Y                           10178
#define IDS_LATITUDE                    10179
#define IDS_LONGITUDE                   10180
#define IDS_POINTS                      10181
#define IDS_TELEPHONE                   10182
#define IDS_FAX                         10183
#define IDS_EMAIL                       10184
#define IDS_LATLON                      10185
#define IDS_XY                          10186
#define IDS_PERCENTSYM                  10187
#define IDS_GREATERTHAN                 10188
#define IDS_INRANGE                     10189
#define IDS_GREATEREQUAL                10190
#define IDS_NEW                         10191
#define IDS_SCALE                       10192
#define IDS_YEAR                        10193
#define IDS_MONTH                       10194
#define IDS_OPEN                        10195
#define IDS_GIFFILE                     10196
#define IDS_BROWSE                      10197
#define IDS_PIECHART                    10198
#define IDS_SHAPEFILECOL                10199
#define IDS_SELFROMTO                   10200
#define IDS_DSNPREFIX                   10201
#define IDS_MAPPROP                     10202
#define IDS_MAP                         10203
#define IDS_QUERYERROR                  10204
#define IDS_GENERAL                     10205
#define IDS_OK                          10205
#define IDS_ADDNEW                      10206
#define IDS_ALLFILES                    10207
#define IDS_LEGEND                      10208
#define IDS_TIMESERIESREPORT            10209
#define IDS_NOFILEFEATURE               10210
#define IDS_READING                     10211
#define IDS_WRITING                     10212
#define IDS_NOCOORDATTR                 10213
#define IDS_NOPOLYLINEATTR              10214
#define IDS_ADDMAPATTR                  10215
#define IDS_NONAMEATTR                  10216
#define IDS_IMPORTTABLETIP              10217
#define IDS_NONAMEATTR2                 10218
#define IDS_ADDNAME                     10218
#define IDS_JPGFILE                     10219
#define IDS_TITLE                       10220
#define IDS_CANCEL                      10221
#define IDS_SELECTALL_T                 10222
#define IDS_DESELECTALL_T               10223
#define IDS_SELECT                      10224
#define IDS_DELETE                      10225
#define IDS_UPDATE                      10226
#define IDS_SECTOR                      10227
#define IDS_FTYPE                       10228
#define IDS_SYMBOLS                     10228
#define IDS_ATTR                        10229
#define IDS_COLUMNS                     10229
#define IDS_COMMENTS                    10230
#define IDS_JANS                        10231
#define IDS_FEBS                        10232
#define IDS_MARS                        10233
#define IDS_APRS                        10234
#define IDS_MAYS                        10235
#define IDS_JUNS                        10236
#define IDS_JULS                        10237
#define IDS_AUGS                        10238
#define IDS_SEPS                        10239
#define IDS_OCTS                        10240
#define IDS_NOVS                        10241
#define IDS_DECS                        10242
#define IDS_NORTHARROW                  10243
#define IDS_SCALEBAR                    10244
#define IDS_ID                          10245
#define IDS_IMPORTCREATE                10246
#define IDS_STRING10247                 10247
#define IDS_NOFEATURECONT               10248
#define IDS_EDITMAPINST                 10249
#define IDS_POINTSEDITINST              10250
#define IDS_ADDPOINTINST                10251
#define IDS_LONGTEXT                    10252
#define IDS_NATURAL                     10253
#define IDS_BLUES                       10254
#define IDS_GREENS                      10255
#define IDS_AQUATIC                     10256
#define IDS_REDS                        10257
#define IDS_PASTELS                     10258
#define IDS_INVREGCODE                  10259
#define IDS_EQUALTO                     10260
#define IDS_NOEQUALTO                   10261
#define IDS_GREATERTHAN_Q               10262
#define IDS_LESSTHAN_Q                  10263
#define IDS_GREATEROREQUAL              10264
#define IDS_LESSTHANOREQUAL             10265
#define IDS_CONTAINS                    10266
#define IDS_COUNTUNIQUE                 10267
#define IDS_SELATTR                     10268
#define IDS_GROUPBYATTRSAME             10269
#define IDS_NOMESSAGE                   10270
#define IDS_TOTALLENGTH                 10271
#define IDS_NOTCONTAINS                 10272
#define IDS_PNGFILE                     10273
#define IDS_IMAGE                       10274
#define IDS_IMAGETYPE                   10275
#define IDS_HOTLINK                     10276
#define IDS_LIKE                        10277
#define IDS_REPORTSETTINGS              10278
#define IDS_ORGANISATION                10279
#define IDS_ADDRESS                     10280
#define IDS_CITY                        10281
#define IDS_PROVINCE                    10282
#define IDS_COUNTRY                     10283
#define IDS_LOGO                        10284
#define IDS_STYLE                       10285
#define IDS_EQUALINTERVALS              10286
#define IDS_PERCENTILES                 10287
#define IDS_NATURALBREAKS               10288
#define IDS_DEFAULT                     10289
#define IDS_SAVING                      10290
#define IDS_SHAPEFILENOPOLYLINES        10291
#define IDS_VALUE                       10292
#define IDS_LABELS                      10293
#define IDS_LABELSANDGRID               10294
#define IDS_PROJECTION                  10295
#define IDS_LAYOUT                      10296
#define IDS_AREASQM                     10297
#define IDS_ERRORS                      10298
#define IDS_ZONE                        10299
#define IDS_NORTH                       10300
#define IDS_SOUTH                       10301
#define IDS_CENTRALMERIDIAN             10302
#define IDS_IMPORTNEW                   10303
#define IDS_NOPRINTER                   10304
#define IDS_LENGTHM                     10305
#define IDS_LOCATOR                     10306
#define IDS_LEFT                        10307
#define IDS_RIGHT                       10308
#define IDS_TOP                         10309
#define IDS_BOTTOM                      10310
#define IDS_CENTROID                    10311
#define IDS_SQMETERS                    10312
#define ID_FILE_SETUP_FEATURETYPES      32774
#define ID_FILE_SETUP_FEATURES          32775
#define ID_FILE_SETUP_ATTRIBUTESTYPES   32776
#define ID_VIEW_MAP                     32777
#define ID_VIEW_ZOOMIN                  32778
#define ID_VIEW_ZOOMOUT                 32779
#define ID_VIEW_ZOOMNORMAL              32780
#define IDS_IMPORT                      32781
#define IDS_COLATTR                     32782
#define IDS_NRDBCAPS                    32783
#define IDS_NRDBSM                      32784
#define ID_REPORT_TABLE                 32796
#define ID_REPORT_GRAPH                 32797
#define ID_IMPORT_ODBC                  32799
#define ID_FILE_ODBC_ADMINSTRATOR       32800
#define ID_VIEW_LAYERS                  32805
#define ID_DRAGMODE                     32808
#define ID_TOOLS_LL2UTM                 32815
#define ID_GOBACK                       32818
#define ID_GOFORWARD                    32819
#define ID_REPORT_SUMMARY               32823
#define ID_REPORT_TSGRAPH               32824
#define ID_TOOLS_PROJECTIONS            32825
#define ID_TOOLS_SETTINGS               32827
#define ID_MAP_EDITDATA                 32830
#define ID_MAP_EDITFEATURE              32831
#define ID_REPORT_WIZARD                32835
#define ID_REPORT_WIZARD_SETUP          32836
#define ID_IMPORT_SHAPEFILE             32838
#define ID_IMPORT_FILE                  32839
#define ID_CONVERT_SHAPEFILE            32840
#define ID_EXPORT_SHAPEFILE             32841
#define ID_FILE_LOGOUT                  32842
#define ID_REPORT_PREVIOUS              32844
#define ID_GRAPH_PROP                   32846
#define ID_HELP_CONTENTS                32847
#define ID_HELP_NRDBHOMEPAGE            32849
#define ID_HELP_TUTORIALDATABASESETUP   32850
#define ID_SCALE                        32851
#define ID_REPORT_PIECHART              32852
#define ID_HELP_SUPPORT                 32853
#define ID_HELP_TUTORIALDEMONSTRATIONDATABASE 32854
#define ID_HELP_NRDBTUTORIAL            32855
#define ID_MAP_SECTORALREPORT           32856
#define ID_REPORT_TIMESERIES            32857
#define ID_MAP_VIEWIMAGE                32858
#define ID_MAP_VIEWFILE                 32859
#define ID_EDIT_SEARCH                  32860
#define ID_MAP_ADDFEATURE               32863
#define ID_BUTTON32864                  32864
#define ID_BUTTON32865                  32865
#define ID_BUTTON32866                  32866
#define ID_BUTTON32867                  32867
#define ID_BUTTON32868                  32868
#define ID_BUTTON32869                  32869
#define ID_BUTTON32870                  32870
#define ID_BUTTON32871                  32871
#define ID_BUTTON32872                  32872
#define ID_BUTTON32873                  32873
#define ID_BUTTON32874                  32874
#define ID_BUTTON32875                  32875
#define ID_BUTTON32876                  32876
#define ID_BUTTON32877                  32877
#define ID_BUTTON32878                  32878
#define ID_BUTTON32879                  32879
#define ID_BUTTON32880                  32880
#define ID_BUTTON32881                  32881
#define ID_BUTTON32882                  32882
#define ID_BUTTON32883                  32883
#define ID_BUTTON32884                  32884
#define ID_BUTTON32885                  32885
#define ID_BUTTON32886                  32886
#define ID_MAP_DELETE                   32888
#define ID_MAP_LAYOUT                   32891
#define ID_EXPLORER                     32892
#define ID_EXPLORER_ADD                 32895
#define ID_EXPLORER_EDIT                32896
#define ID_EXPLORER_EDITDATA            32897
#define ID_EXPLORER_DELETE              32898
#define ID_EXPLORER_MAPOPEN             32900
#define ID_EXPLORER_MAPDELETE           32901
#define ID_EXPLORER_MAPNEW              32902
#define ID_MAP_LATLON                   32903
#define ID_MAP_EDITLINES                32905
#define ID_MAP_EDITPOINTS               32906
#define ID_MAP_PAN                      32907
#define ID_MAP_MEASURE                  32908
#define ID_MAP_AUTOUPDATE               32909
#define ID_MAP_UPDATE                   32910
#define ID_SCHEME_DELETE                32911
#define ID_SCHEME_SAVE                  32912
#define ID_ADVANCED                     32913
#define ID_PROPERTIES                   32914
#define ID_BUTTON32916                  32916
#define ID_LAYOUT_MAP                   32916
#define ID_LAYOUT_LEGEND                32917
#define ID_LAYOUT_TITLE                 32918
#define ID_LAYOUT_ARROW                 32919
#define ID_LAYOUT_SCALEBAR              32920
#define ID_LAYOUT_PROJECTION            32921
#define ID_LAYOUT_BORDER                32923
#define ID_LAYOUT_TEXT                  32924
#define ID_LAYOUT_PICTURE               32925
#define ID_SYMBOLS_ADD                  32926
#define IDS_BORDER                      32926
#define ID_SYMBOLS_DELETE               32927
#define ID_MAP_GRID                     32928
#define ID_LAYOUT_SELECT                32929
#define ID_BUTTON32930                  32930
#define ID_LAYOUT_SOURCE                32931
#define ID_LAYOUT_SCALE                 32932
#define ID_LAYOUT_PREVIEW               32933
#define ID_MAP_NEWLINE                  32935
#define ID_MAP_LOCATOR                  32936
#define ID_MAP_VIEWATTR                 32937
#define ID_HELP_REGISTER                32938

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        288
#define _APS_NEXT_COMMAND_VALUE         32940
#define _APS_NEXT_CONTROL_VALUE         1324
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
