//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by StatSimPro.rc
//
#define IDC_EDIT                        3
#define IDC_AUTOSELECTOPT               3
#define IDC_AUTOSEL                     3
#define IDC_OPT_KEY                     3
#define IDC_SELECT                      4
#define IDC_SPECPATHOPT                 4
#define IDC_ADD                         4
#define IDC_REMOVE                      5
#define IDC_SECT_GO                     5
#define IDC_OPT_SELECT                  5
#define IDC_DESELECT                    6
#define IDC_CLEAR                       6
#define IDC_FIG_GO                      6
#define IDC_DISPLAY                     6
#define IDC_CLOSE                       6
#define IDC_REMOVE2                     6
#define IDC_SELECTALL                   7
#define IDC_UPDATE                      7
#define IDC_DESELECTALL                 8
#define IDC_DEFN                        8
#define IDC_SELECT2                     9
#define IDC_SELECTTAB                   9
#define IDC_DESELECT2                   10
#define IDC_DESELECTTAB                 10
#define IDC_VAREXP                      11
#define IDC_LINK                        12
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDD_SSFORMVIEW                  101
#define IDS_STATSIM_DESC                101
#define IDS_STRING102                   102
#define IDD_PROGRESSDLGBAR              103
#define IDD_SSPROGRESSDIALOG            104
#define IDR_HTML_CUSTOMTABLEDLG         105
#define IDR_HTML_EDITTHRESHDLG          109
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_StatSimSGETYPE              129
#define IDR_SSHTMLView                  129
#define IDR_StatSimProTYPE              130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_WINDOWS_MANAGER              132
#define ID_VIEW_DATAVIEW                133
#define IDI_ICON1                       133
#define IDI_KEYS                        133
#define ID_VIEW_REPORTVIEW              134
#define IDD_PROGRESSDLG                 134
#define ID_PROPERTIES                   135
#define IDD_EDITLEVELDLG                135
#define ID_OPEN                         136
#define IDR_EDITLEVEL                   136
#define ID_OPEN_WITH                    137
#define IDB_FGLOBE                      137
#define IDR_INDWIZDLG                   137
#define ID_DUMMY_COMPILE                138
#define IDD_PROCSELDLG                  138
#define IDB_HGLOBE                      138
#define ID_REPORT_ADD_MEMBER_FUNCTION   139
#define IDB_GLOBE                       139
#define IDD_SWITCH                      139
#define ID_REPORT_ADD_MEMBER_VARIABLE   140
#define IDD_IMPORTSELPATH               140
#define ID_REPORT_DEFINITION            141
#define IDD_IMPORTAUTOSEL               141
#define ID_REPORT_PROPERTIES            142
#define IDD_INDWIZDLG                   142
#define ID_NEW_FOLDER                   143
#define IDD_SELEINDDLG                  143
#define ID_SORT_MENU                    144
#define IDD_INDEDITDLG                  144
#define ID_SORTING_GROUPBYTYPE          145
#define IDB_LOGIN                       145
#define IDD_CONFIGDLG                   145
#define ID_SORTING_SORTALPHABETIC       146
#define IDB_TXTFILE                     146
#define IDD_PROGRESSEXDLG               146
#define ID_SORTING_SORTBYTYPE           147
#define IDB_CBMSLOGO                    147
#define IDD_DATADEFNDLG                 147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDI_UNCHECKED                   151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define IDI_CHECKED                     152
#define ID_PROPERTIES2                  153
#define IDI_NOCHECK                     153
#define ID_EXPAND_ALL                   154
#define IDI_PARTIALLY                   154
#define IDS_DATA_VIEW                   155
#define IDI_GLOBE                       155
#define IDS_REPORT_VIEW                 156
#define IDI_GLOBEOK                     156
#define IDS_OUTPUT_WND                  157
#define IDI_FFWD                        157
#define IDS_PROPERTIES_WND              158
#define IDI_FREW                        158
#define IDI_REW                         159
#define IDI_FWD                         160
#define IDI_DATA_VIEW                   161
#define IDI_FFWD1                       161
#define IDI_NOTEPAD                     161
#define IDI_DATA_VIEW_HC                162
#define IDI_REPORT                      162
#define IDI_REPORT_VIEW                 163
#define IDI_DATA                        163
#define IDI_REPORT_VIEW_HC              164
#define IDI_ICON4                       164
#define IDI_MAP                         164
#define IDI_OUTPUT_WND                  165
#define IDB_TREEDOWNARROW               165
#define IDI_DOWNWIZ                     165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDD_TREETESTDLG                 167
#define IDI_PROPERTIES_WND_HC           168
#define IDD_CUSTOMTABLEDLG              168
#define IDR_EXPLORER                    169
#define IDD_LINKMGRDLG                  169
#define IDI_NOCHECK1                    169
#define IDI_TEXTFILE                    169
#define IDB_EXPLORER_24                 170
#define IDD_VXBUILDDLG                  170
#define IDR_SORT                        171
#define IDD_EDITTABLEDLG                171
#define IDB_SORT_24                     172
#define IDD_MERGEDATADLG                172
#define IDR_POPUP_SORT                  173
#define IDD_EXESQLDLG                   173
#define IDR_POPUP_EXPLORER              174
#define IDD_EDITTHRESHDLG               174
#define IDB_DATA_VIEW                   175
#define IDD_SELDATADLG                  175
#define IDB_DATA_VIEW_24                176
#define IDB_REPORT_VIEW                 177
#define IDB_REPORT_VIEW_24              178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_VIEW_NAVIGATION              185
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_DATA                 280
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDR_RIBBON1                     308
#define IDR_HTML_S                      310
#define IDS_RIBBON_STATS                313
#define IDS_RIBBON_IMPORT               314
#define IDS_RIBBON_EXPORT               315
#define IDB_FILE_VIEW                   316
#define IDB_FILE_VIEW_24                317
#define IDB_NAVIGATION_LARGE            318
#define IDB_NAVIGATION_LARGE_HC         319
#define IDR_HTML1                       326
#define IDC_LABELHOST                   1000
#define IDC_EDITHOST                    1001
#define IDC_TEXTHOST                    1001
#define IDC_LABELPORT                   1002
#define IDC_EDITPORT                    1003
#define IDC_TEXTPORT                    1003
#define IDC_LABELUSER                   1004
#define IDC_EDITUSER                    1005
#define IDC_TEXTUSER                    1005
#define IDC_EDIT1                       1005
#define IDC_EDIT_ABT                    1005
#define IDC_LABELPWD                    1006
#define IDC_SELARCHIVE                  1006
#define IDC_SELCAN                      1006
#define IDC_EDITPWD                     1007
#define IDC_TEXTPWD                     1007
#define IDC_COMBODB                     1008
#define IDC_LABELDB                     1009
#define IDC_PROGRESSBAR                 1009
#define IDC_PROGRESSLABEL               1010
#define IDC_LISTLEVELNAV                1011
#define IDC_LISTLEVEL                   1012
#define IDC_TEXTSELECT                  1013
#define IDC_FRAMESELECT                 1018
#define IDC_LISTUNSEL                   1019
#define IDC_BANNER                      1020
#define IDC_FRAMESELECT2                1020
#define IDC_LISTSEL                     1021
#define IDC_LISTPATH                    1021
#define IDC_TREELEVEL                   1022
#define IDC_SPECIFYPATH                 1023
#define IDC_INDCAT                      1025
#define IDC_INDSECT                     1026
#define IDC_INDFIG                      1027
#define IDC_LABEL_CAT                   1028
#define IDC_CAT_GO                      1029
#define IDC_LABEL_SECT                  1030
#define IDC_LABEL_FIG                   1031
#define IDC_TXT_DESC                    1032
#define IDC_LABEL_DESC                  1033
#define IDC_COMBO_EIND                  1033
#define IDC_FRAME_INDEDIT               1034
#define IDC_COMBOLEVEL                  1037
#define IDC_EDIT_VAR                    1040
#define IDC_LABEL_VAR                   1041
#define IDC_VIEW                        1041
#define IDC_CHANGE                      1042
#define IDC_TABSWITCH                   1044
#define IDC_LISTSGE                     1045
#define IDC_PROGRESSLIST                1046
#define IDC_FRAMELIST                   1047
#define IDC_LISTDATADEFN                1056
#define IDC_PROGRESS_CTRL               1057
#define IDC_STATIC_TEXT1                1058
#define IDC_STATIC_TEXT2                1059
#define IDC_STATIC_TEXT3                1060
#define IDC_COMBO_PARE                  1064
#define IDC_EDIT_CHE                    1065
#define IDC_COMBO_RELNK                 1065
#define IDC_EDIT_EIND                   1066
#define IDC_COMBO_RVLNK                 1066
#define IDC_COMBO_CHE                   1067
#define IDC_EDIT_LVLNK                  1067
#define IDC_EDIT_EDESC                  1068
#define IDC_EDIT_RVLNK                  1068
#define IDC_LIST_SELSRC                 1069
#define IDC_COMBO_LELNK                 1070
#define IDC_LIST_UNSELSRC               1070
#define IDC_EDIT_LABELLNK               1071
#define IDC_COMBO_LVLNK                 1072
#define IDC_COMBO_VLNK                  1073
#define IDC_LADV                        1074
#define IDC_RADV                        1075
#define IDC_COMBO_SRC                   1075
#define IDC_LIST_LNK                    1076
#define IDC_COMBO_VETYPE                1076
#define IDC_COMBO_EXP                   1077
#define IDC_EDIT_ALIAS                  1078
#define IDC_COMBO_VAR                   1079
#define IDC_COMBO_VERELP                1080
#define IDC_COMBO_VEVAL                 1081
#define IDC_EDIT_VEVAL                  1082
#define IDC_EDIT_VELABEL                1083
#define IDC_EDIT_VE                     1084
#define IDC_ADVEDIT                     1085
#define IDC_LABELS                      1086
#define IDC_LIST_VE                     1087
#define IDC_EDIT_SUBTHRESH              1087
#define IDC_EDIT_ELEMENT                1088
#define IDC_FRAME_UNSELSRC              1089
#define IDC_LIST_MASTER                 1090
#define IDC_COMBO_MASTER                1091
#define IDC_COMBO_USING                 1092
#define IDC_LIST_MASTER2                1093
#define IDC_LIST_USING                  1093
#define IDC_FRAME                       1093
#define IDC_LIST_MERGE                  1094
#define IDC_RUN                         1094
#define IDC_EDIT_SQL                    1095
#define IDC_COMBO_DATA                  1096
#define IDC_LABEL_PROVINCE              1142
#define IDC_LABEL_MUNICIPALITY          1143
#define IDC_LABEL_YEAR                  1144
#define IDC_COMBO_YEAR                  1145
#define IDC_COMBO_PROVINCE              1146
#define IDC_COMBO_URBANITY              1147
#define IDC_LABEL_URBANITY              1148
#define IDC_FRAME_THRESHOLDS            1149
#define IDC_LABEL_POVTHRESH             1150
#define IDC_EDIT_POVTHRESH              1151
#define IDC_LABEL_SUBTHRESH             1152
#define IDC_COMBO_MUNICIPALITY          1153
#define IDD_LOGIN                       1319
#define IDD_REMOVEAUTOSEL2              1320
#define IDD_CLEARSELHH                  1321
#define IDD_CMDDLG                      1322
#define ID_FILE_IMPORT                  27471
#define ID_FILE_EXPORT                  27472
#define IDR_RIBBON_BAK                  30800
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_LEVEL_EDIT                   32771
#define ID_LEVEL_DELETE                 32772
#define ID_FILE_I                       32773
#define ID_DATA_CLEARHOUSEHOLDS         32778
#define ID_BUTTON2                      32778
#define ID_DATA_CLEAR_BPQ               32778
#define ID_DATA_CLEARHH                 32779
#define ID_DATA_CLEARSELHH              32780
#define ID_DATA_RESET                   32781
#define ID_DATA_EDITTHRESH              32782
#define ID_DATA_FETCHDATA               32783
#define ID_DATA_PROCESSANDUPDATE        32784
#define ID_FILE_EXPORT_MDG              32784
#define ID_DATA_QUESTIONNAIRE           32785
#define ID_DATA_MATCHING                32786
#define ID_RIBCOMB_DB                   32786
#define ID_DATA_UPDATE                  32788
#define ID_DATA_QNR                     32789
#define ID_DATA_MATCH                   32790
#define ID_DATA_PROCMDG                 32791
#define ID_STATS_WIZARD                 32792
#define ID_STATS_COMPUTE                32793
#define ID_STATS_EXECUTESQL             32794
#define ID_STATS_EXESQL                 32795
#define ID_STATS_TABLES                 32796
#define ID_CALL_STATSIM4                32796
#define ID_TABLES_DEFINETABLE           32797
#define ID_FILE_EXPORT_CCI              32798
#define ID_TABLES_CROSSTABULATION       32799
#define ID_STATS_CSPROCROSSTABS         32800
#define ID_CALL_NOTEPAD                 32800
#define ID_STATS_CSPROXTABS             32801
#define ID_BUTTON3                      32801
#define ID_TABLES_DEFINETAB             32802
#define ID_TAB_NEW_RPT                  32802
#define ID_STATS_CMD                    32803
#define ID_TABLES_XTAB                  32804
#define IDC_IND_DISPLAY                 32805
#define IDC_IND_ADD                     32806
#define ID_EXPORT_LEGACY                32806
#define ID_INDICATOR_EDIT               32807
#define ID_BUTTON4                      32807
#define IDC_IND_EDIT                    32808
#define ID_BUTTON6                      32808
#define IDC_IND_DELETE                  32809
#define ID_INDICATOR_CUSTOMIZE          32810
#define ID_BUTTON8                      32810
#define ID_CUSTOMIZE_IDC                32811
#define IDC_IND_CUSTTABLE               32812
#define ID_FILE_EXPORT_CCI_CSV          32812
#define ID_STATS_INDWIZ                 32813
#define ID_TAB_NEW_PORTAL               32814
#define ID_FILE_EXPORT_RAW_DATA_TAB     32821
#define ID_FILE_EXPORT_RAW_DATA_CSV     32822
#define ID_FILE_EXPORT_RAW_DATA_MDB     32823
#define ID_FILE_EXPORT_NRDB             32824
#define ID_FILE_EXPORT_DATA             32825
#define ID_EDIT_THRESH                  32826
#define ID_STATS_DEFINETAB              32827
#define ID_STATS_CSPROXTAB_HH           32830
#define ID_STATS_CSPROXTAB_BRGY         32831
#define ID_CALL_NRDB                    32832
#define ID_CALL_ENCODE                  32833
#define ID_DATA_PROCCCRI                32834
#define ID_DATA_PROCBPQ                 32835
#define ID_FILE_EXPORT_BPQIND           32836
#define ID_TABLES_SUMMARYTABLES         32837
#define ID_DATA_FETCH                   32839
#define ID_TABLES_SUMMTAB               32840
#define ID_DATA_PROCOKI                 32841
#define ID_DATA_ATTCLEAN                32842
#define ID_FILE_EXPORT_CORE_CSV         32843
#define ID_FILE_EXPORT_MDG_CSV          32844

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        327
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
