package dlg;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.TextArea;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author joebanc
 */
public class Main extends javax.swing.JFrame {
	private JTabbedPane jtabMain;
	private	JPanel ribpanel1;
	private	JPanel ribpanel2;
	private	JPanel ribpanel3;

    /**
     * Creates new form Main
     */
    public Main() {
        //from initcomponents
        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        //initComponents();
        setTitle( "STATSIM Main" );
        setSize( 900, 600 );
        setBackground( Color.gray );
        
        JPanel topPanel = new JPanel();
        topPanel.setLayout( new BorderLayout() );
        getContentPane().add( topPanel );
        
        // Create the tab pages
        createPage1();
        createPage2();
        createPage3();
        
        // Create a tabbed pane
        jtabMain = new JTabbedPane();
        jtabMain.addTab( "Page 1", ribpanel1 );
        jtabMain.addTab( "Page 2", ribpanel2 );
        jtabMain.addTab( "Page 3", ribpanel3 );
        topPanel.add( jtabMain, BorderLayout.CENTER );
        
    }
    public void createPage0()
    {
        ribpanel1 = new JPanel();
        ribpanel1.setLayout( null );
        
        JLabel label1 = new JLabel( "Username:" );
        label1.setBounds( 10, 15, 150, 20 );
        ribpanel1.add( label1 );
        
        JTextField field = new JTextField();
        field.setBounds( 10, 35, 150, 20 );
        ribpanel1.add( field );
        
        JLabel label2 = new JLabel( "Password:" );
        label2.setBounds( 10, 60, 150, 20 );
        ribpanel1.add( label2 );
        
        JPasswordField fieldPass = new JPasswordField();
        fieldPass.setBounds( 10, 80, 150, 20 );
        ribpanel1.add( fieldPass );
    }
    public void createPage1()
    {
        ribpanel1 = new JPanel();
        ribpanel1.setLayout( null );
        
        JSplitPane  jsplitRpt = new JSplitPane();
        jsplitRpt.setDividerLocation(250);
        jsplitRpt.setDividerSize(5);
        jsplitRpt.setName(""); 
        
        ribpanel1.add( jsplitRpt );
        
    }
    
    public void createPage2()
    {
        ribpanel2 = new JPanel();
        ribpanel2.setLayout( new BorderLayout() );
        
        ribpanel2.add( new JButton( "North" ), BorderLayout.NORTH );
        ribpanel2.add( new JButton( "South" ), BorderLayout.SOUTH );
        ribpanel2.add( new JButton( "East" ), BorderLayout.EAST );
        ribpanel2.add( new JButton( "West" ), BorderLayout.WEST );
        ribpanel2.add( new JButton( "Center" ), BorderLayout.CENTER );
    }
    
    public void createPage3()
    {
        ribpanel3 = new JPanel();
        ribpanel3.setLayout( new GridLayout( 3, 2 ) );
        
        ribpanel3.add( new JLabel( "Field 1:" ) );
        ribpanel3.add( new TextArea() );
        ribpanel3.add( new JLabel( "Field 2:" ) );
        ribpanel3.add( new TextArea() );
        ribpanel3.add( new JLabel( "Field 3:" ) );
        
        ribpanel3.add( new TextArea() );
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
